"""initial

Revision ID: 67606cb18c20
Revises: 
Create Date: 2025-05-18 16:38:10.938467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67606cb18c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('watering', sa.String(), nullable=True),
    sa.Column('sunlight', sa.String(), nullable=True),
    sa.Column('growth_rate', sa.String(), nullable=True),
    sa.Column('care_level', sa.String(), nullable=True),
    sa.Column('maintenance', sa.String(), nullable=True),
    sa.Column('soil', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
